### ISSUE TITLE
correct unmodified Raspbian image

### ISSUE THREAD

**Issue by zpzigi** [Microsoft/Komodo#17]
Hello. I am trying to install and run Komodo in QEMU environment.
In readme, it is mentioned that 
`GUEST_DISKIMG` should point to the unmodified Raspbian image.
Howver, there are a lot of Raspbian images in http://downloads.raspberrypi.org/raspbian/images/.
I've tested with several ones, but they all failed to run Komodo.

Could you please inform that which Raspbian image should I use?
If it is possible, I hope to know the exact version of Raspbian image which Komodo's developers have used.
Thanks in advance.

**Comment by 0xabu** [comment]
Looking at the image we used, I see that `/etc/os-release` contains:
```
Raspberry Pi reference 2016-05-10
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, c32099002b4c44243e87d8cc90303237eb5ce06a, stage2
```

So my guess would be that [this](http://downloads.raspberrypi.org/raspbian/images/raspbian-2016-05-13/) is the correct image.
