### ISSUE TITLE
There was a problem when running make in the top-level directory

### ISSUE THREAD

**Issue by hz1490919302** [microsoft/Komodo#19]
![QQ截图20191204214953](https://user-images.githubusercontent.com/27117133/70147812-00324000-16e0-11ea-9c76-1fbef2a12daa.png)

**Comment by 0xabu** [comment]
What environment are you building on? Native Linux, Cygwin or WSL? Based on this build output, it appears to be one of the latter, but the native vale.exe executable has a problem. Can you run `tools/vale/bin/vale.exe` on its own? Can you run it from a CMD prompt?

**Comment by hz1490919302** [comment]
I have solved the problem.I am building on the WSL.So I use `mono bin / vale.exe` instead of `vale.exe`. Thank you very much.

**Comment by hz1490919302** [comment]
Sorry, I encountered another problem. The modules **_lemma__ARM__L2PTE__helper_** and **_lemma__nonexec__mapping_** in the file **_verified / ptebits.i.dfy_** timed out during validation,which causes running make to fail.
According to the description, these modules should complete verification in 90 seconds, but they exceed 90 seconds.
![QQ截图20191205192421](https://user-images.githubusercontent.com/27117133/70232173-cc662180-1796-11ea-98dc-8e7ce02c331b.png)
![QQ截图20191205192434](https://user-images.githubusercontent.com/27117133/70232179-cec87b80-1796-11ea-8a92-5b9e87dac79d.png)
![QQ截图20191205192513](https://user-images.githubusercontent.com/27117133/70232185-d1c36c00-1796-11ea-847a-225a4cdda0a5.png)
![QQ截图20191205192853](https://user-images.githubusercontent.com/27117133/70232192-d38d2f80-1796-11ea-83d3-0d0c17280d5e.png)

**Comment by 0xabu** [comment]
> I have solved the problem.I am building on the WSL. So I use `mono bin / vale.exe` instead of `vale.exe`. Thank you very much.
Interesting. Mono shouldn't be required to run .NET binaries on WSL. I'm guessing that you're using the new VM-based WSL2, and something has changed in this respect.

> Sorry, I encountered another problem. The modules **_lemma__ARM__L2PTE__helper_** and **_lemma__nonexec__mapping_** in the file **_verified / ptebits.i.dfy_** timed out during validation,which causes running make to fail.
> According to the description, these modules should complete verification in 90 seconds, but they exceed 90 seconds.

Timeouts are a known issue. See #1, and #7 for a possible workaround.
